### ISSUE TITLE
Any plans for more operations?

### ISSUE THREAD

**Issue by stevehansen** [PixelByProxy/AsusRouterTools#4]
Are there any plans to also add extra features for example changing data?

**Comment by PixelByProxy** [comment]
I may add them as requested. Are you looking for anything in particular?

**Comment by stevehansen** [comment]
One of the use cases was for the IPv6 firewall, I'm exposing some virtual machines for rdp and sometimes the IP address changed, so I was looking for automating it so that it will also keep the firewall list up-to-date with the VM addresses

![image](https://user-images.githubusercontent.com/2143488/209240019-f2e5b387-fdca-496d-bc60-e6f315c5060f.png)

**Comment by PixelByProxy** [comment]
I'm looking into this. I have [a branch](https://github.com/PixelByProxy/AsusRouterTools/tree/feature/firewall) that has a GET for the firewall rules so far. Looks like it will be pretty straight forward to add the SET but I'm still investigating.

**Comment by PixelByProxy** [comment]
Hi @stevehansen, version 1.0.42 that has a new FirewallService that can read and write firewall rules. Please note that the router API overwrites any existing rules, so you'll want to make sure you do a GET on the firewall rules before modifying to ensure you don't lose anything. Also note that you have to set EnableWrite on the AsusConfiguration to true or the SET will throw an exception. I have marked the write behavior as experimental since this is the first API that allows a write operation, please use with caution and make sure to backup any of your settings before trying this yourself.
